# Generated by Django 5.1.4 on 2024-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(choices=[('+1', '+1 (USA)'), ('+91', '+91 (India)'), ('+44', '+44 (UK)'), ('+61', '+61 (Australia)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+39', '+39 (Italy)'), ('+7', '+7 (Russia)'), ('+27', '+27 (South Africa)'), ('+55', '+55 (Brazil)'), ('+34', '+34 (Spain)'), ('+62', '+62 (Indonesia)'), ('+63', '+63 (Philippines)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+971', '+971 (UAE)'), ('+92', '+92 (Pakistan)'), ('+972', '+972 (Israel)'), ('+94', '+94 (Sri Lanka)'), ('+880', '+880 (Bangladesh)'), ('+1', '+1 (Canada)'), ('+598', '+598 (Uruguay)'), ('+353', '+353 (Ireland)'), ('+47', '+47 (Norway)'), ('+46', '+46 (Sweden)'), ('+48', '+48 (Poland)'), ('+52', '+52 (Mexico)'), ('+351', '+351 (Portugal)'), ('+90', '+90 (Turkey)'), ('+82', '+82 (South Korea)'), ('+98', '+98 (Iran)'), ('+234', '+234 (Nigeria)'), ('+254', '+254 (Kenya)'), ('+255', '+255 (Tanzania)'), ('+260', '+260 (Zambia)'), ('+263', '+263 (Zimbabwe)')], default='', max_length=5)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('company_stage', models.CharField(choices=[('idea', 'Idea Stage'), ('startup', 'A Startup'), ('smb', 'A SMB'), ('enterprise', 'An Enterprise')], max_length=50)),
                ('help_with', models.CharField(max_length=255)),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_us_name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('join_us_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('join_us_country_code', models.CharField(choices=[('+1', '+1 (USA)'), ('+91', '+91 (India)'), ('+44', '+44 (UK)'), ('+61', '+61 (Australia)'), ('+81', '+81 (Japan)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+39', '+39 (Italy)'), ('+7', '+7 (Russia)'), ('+27', '+27 (South Africa)'), ('+55', '+55 (Brazil)'), ('+34', '+34 (Spain)'), ('+62', '+62 (Indonesia)'), ('+63', '+63 (Philippines)'), ('+64', '+64 (New Zealand)'), ('+20', '+20 (Egypt)'), ('+971', '+971 (UAE)'), ('+92', '+92 (Pakistan)'), ('+972', '+972 (Israel)'), ('+94', '+94 (Sri Lanka)'), ('+880', '+880 (Bangladesh)'), ('+1', '+1 (Canada)'), ('+598', '+598 (Uruguay)'), ('+353', '+353 (Ireland)'), ('+47', '+47 (Norway)'), ('+46', '+46 (Sweden)'), ('+48', '+48 (Poland)'), ('+52', '+52 (Mexico)'), ('+351', '+351 (Portugal)'), ('+90', '+90 (Turkey)'), ('+82', '+82 (South Korea)'), ('+98', '+98 (Iran)'), ('+234', '+234 (Nigeria)'), ('+254', '+254 (Kenya)'), ('+255', '+255 (Tanzania)'), ('+260', '+260 (Zambia)'), ('+263', '+263 (Zimbabwe)')], default='', max_length=5)),
                ('join_us_phone_number', models.CharField(default='', max_length=15)),
                ('position_applying_for', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('sales-representative', 'Sales Representative'), ('marketing-specialist', 'Marketing Specialist')], max_length=50, verbose_name='Position Applying For')),
                ('location', models.CharField(max_length=255, verbose_name='Where are you based?')),
                ('file_upload', models.FileField(upload_to='Resume/', verbose_name='Upload Your Resume')),
                ('join_us_message', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Join Us',
            },
        ),
    ]
