# Generated by Django 4.2 on 2025-03-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_meta_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_meta_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
